%-----------------------------------------------------------------------
% Job saved on 26-Jul-2025 16:41:37 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.cfg_basicio.file_dir.dir_ops.cfg_mkdir.parent = {'D:\project\raw_data_2\sub-EESS001'};
matlabbatch{1}.cfg_basicio.file_dir.dir_ops.cfg_mkdir.name = 'Analysis';
matlabbatch{2}.cfg_basicio.file_dir.dir_ops.cfg_mkdir.parent(1) = cfg_dep('Make Directory: Make Directory ''Analysis''', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','dir'));
matlabbatch{2}.cfg_basicio.file_dir.dir_ops.cfg_mkdir.name = '1st_level';
matlabbatch{3}.spm.stats.fmri_spec.dir(1) = cfg_dep('Make Directory: Make Directory ''1st_level''', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','dir'));
matlabbatch{3}.spm.stats.fmri_spec.timing.units = 'secs';
matlabbatch{3}.spm.stats.fmri_spec.timing.RT = 1.56;
matlabbatch{3}.spm.stats.fmri_spec.timing.fmri_t = 26;
matlabbatch{3}.spm.stats.fmri_spec.timing.fmri_t0 = 13;
%%
matlabbatch{3}.spm.stats.fmri_spec.sess.scans = {
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,1'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,2'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,3'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,4'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,5'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,6'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,7'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,8'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,9'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,10'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,11'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,12'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,13'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,14'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,15'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,16'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,17'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,18'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,19'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,20'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,21'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,22'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,23'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,24'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,25'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,26'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,27'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,28'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,29'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,30'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,31'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,32'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,33'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,34'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,35'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,36'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,37'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,38'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,39'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,40'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,41'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,42'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,43'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,44'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,45'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,46'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,47'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,48'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,49'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,50'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,51'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,52'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,53'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,54'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,55'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,56'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,57'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,58'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,59'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,60'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,61'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,62'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,63'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,64'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,65'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,66'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,67'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,68'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,69'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,70'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,71'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,72'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,73'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,74'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,75'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,76'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,77'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,78'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,79'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,80'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,81'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,82'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,83'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,84'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,85'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,86'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,87'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,88'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,89'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,90'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,91'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,92'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,93'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,94'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,95'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,96'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,97'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,98'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,99'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,100'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,101'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,102'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,103'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,104'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,105'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,106'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,107'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,108'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,109'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,110'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,111'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,112'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,113'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,114'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,115'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,116'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,117'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,118'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,119'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,120'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,121'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,122'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,123'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,124'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,125'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,126'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,127'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,128'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,129'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,130'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,131'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,132'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,133'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,134'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,135'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,136'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,137'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,138'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,139'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,140'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,141'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,142'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,143'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,144'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,145'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,146'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,147'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,148'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,149'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,150'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,151'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,152'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,153'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,154'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,155'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,156'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,157'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,158'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,159'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,160'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,161'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,162'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,163'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,164'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,165'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,166'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,167'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,168'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,169'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,170'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,171'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,172'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,173'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,174'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,175'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,176'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,177'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,178'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,179'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,180'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,181'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,182'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,183'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,184'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,185'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,186'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,187'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,188'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,189'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,190'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,191'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,192'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,193'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,194'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,195'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,196'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,197'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,198'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,199'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,200'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,201'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,202'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,203'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,204'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,205'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,206'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,207'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,208'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,209'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,210'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,211'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,212'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,213'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,214'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,215'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,216'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,217'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,218'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,219'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,220'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,221'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,222'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,223'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,224'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,225'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,226'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,227'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,228'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,229'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,230'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,231'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,232'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,233'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,234'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,235'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,236'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,237'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,238'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,239'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,240'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,241'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,242'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,243'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,244'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,245'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,246'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,247'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,248'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,249'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,250'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,251'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,252'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,253'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,254'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,255'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,256'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,257'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,258'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,259'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,260'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,261'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,262'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,263'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,264'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,265'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,266'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,267'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,268'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,269'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,270'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,271'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,272'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,273'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,274'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,275'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,276'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,277'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,278'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,279'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,280'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,281'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,282'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,283'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,284'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,285'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,286'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,287'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,288'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,289'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,290'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,291'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,292'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,293'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,294'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,295'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,296'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,297'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,298'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,299'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,300'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,301'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,302'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,303'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,304'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,305'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,306'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,307'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,308'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,309'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,310'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,311'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,312'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,313'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,314'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,315'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,316'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,317'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,318'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,319'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,320'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,321'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,322'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,323'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,324'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,325'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,326'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,327'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,328'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,329'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,330'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,331'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,332'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,333'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,334'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,335'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,336'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,337'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,338'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,339'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,340'
                                                 'D:\project\raw_data_2\sub-EESS001\Preprocessing\swasub-EESS001_task-Cyberball_bold.nii,341'
                                                 };
%%
matlabbatch{3}.spm.stats.fmri_spec.sess.cond = struct('name', {}, 'onset', {}, 'duration', {}, 'tmod', {}, 'pmod', {}, 'orth', {});
matlabbatch{3}.spm.stats.fmri_spec.sess.multi = {'D:\project\raw_data_2\sub-EESS001\sub-EESS001_task-Cyberball_timings_nofix.mat'};
matlabbatch{3}.spm.stats.fmri_spec.sess.regress = struct('name', {}, 'val', {});
matlabbatch{3}.spm.stats.fmri_spec.sess.multi_reg = {'D:\project\raw_data_2\sub-EESS001\Preprocessing\rp_asub-EESS001_task-Cyberball_bold.txt'};
matlabbatch{3}.spm.stats.fmri_spec.sess.hpf = 200;
matlabbatch{3}.spm.stats.fmri_spec.fact = struct('name', {}, 'levels', {});
matlabbatch{3}.spm.stats.fmri_spec.bases.hrf.derivs = [0 0];
matlabbatch{3}.spm.stats.fmri_spec.volt = 1;
matlabbatch{3}.spm.stats.fmri_spec.global = 'None';
matlabbatch{3}.spm.stats.fmri_spec.mthresh = 0.8;
matlabbatch{3}.spm.stats.fmri_spec.mask = {''};
matlabbatch{3}.spm.stats.fmri_spec.cvi = 'AR(1)';
matlabbatch{4}.spm.stats.fmri_est.spmmat(1) = cfg_dep('fMRI model specification: SPM.mat File', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{4}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{4}.spm.stats.fmri_est.method.Classical = 1;
matlabbatch{5}.spm.stats.con.spmmat(1) = cfg_dep('Model estimation: SPM.mat File', substruct('.','val', '{}',{4}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{5}.spm.stats.con.consess{1}.tcon.name = 'Linear_trend_excl';
matlabbatch{5}.spm.stats.con.consess{1}.tcon.weights = [3 0 1 0 -1 0 -3];
matlabbatch{5}.spm.stats.con.consess{1}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.consess{2}.tcon.name = 'All_excl > All_incl';
matlabbatch{5}.spm.stats.con.consess{2}.tcon.weights = [3 -4 3 -4 3 -4 3];
matlabbatch{5}.spm.stats.con.consess{2}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.consess{3}.tcon.name = '100 > 0';
matlabbatch{5}.spm.stats.con.consess{3}.tcon.weights = [1 1 0 0 0 0 -2];
matlabbatch{5}.spm.stats.con.consess{3}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.consess{4}.tcon.name = '100excl > 100incl';
matlabbatch{5}.spm.stats.con.consess{4}.tcon.weights = [1 -1 0 0 0 0 0];
matlabbatch{5}.spm.stats.con.consess{4}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.consess{5}.tcon.name = '66excl > 66incl';
matlabbatch{5}.spm.stats.con.consess{5}.tcon.weights = [0 0 1 -1 0 0 0];
matlabbatch{5}.spm.stats.con.consess{5}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.consess{6}.tcon.name = '33excl > 33incl';
matlabbatch{5}.spm.stats.con.consess{6}.tcon.weights = [0 0 0 0 1 -1 0];
matlabbatch{5}.spm.stats.con.consess{6}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.consess{7}.tcon.name = '100excl > 0excl';
matlabbatch{5}.spm.stats.con.consess{7}.tcon.weights = [1 0 0 0 0 0 -1];
matlabbatch{5}.spm.stats.con.consess{7}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.consess{8}.tcon.name = '66excl > 0excl';
matlabbatch{5}.spm.stats.con.consess{8}.tcon.weights = [0 0 1 0 0 0 -1];
matlabbatch{5}.spm.stats.con.consess{8}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.consess{9}.tcon.name = '33excl > 0excl';
matlabbatch{5}.spm.stats.con.consess{9}.tcon.weights = [0 0 0 0 1 0 -1];
matlabbatch{5}.spm.stats.con.consess{9}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.consess{10}.tcon.name = 'average';
matlabbatch{5}.spm.stats.con.consess{10}.tcon.weights = [1 1 1 1 1 1 1];
matlabbatch{5}.spm.stats.con.consess{10}.tcon.sessrep = 'none';
matlabbatch{5}.spm.stats.con.delete = 0;
matlabbatch{6}.spm.stats.results.spmmat(1) = cfg_dep('Contrast Manager: SPM.mat File', substruct('.','val', '{}',{5}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{6}.spm.stats.results.conspec.titlestr = '';
matlabbatch{6}.spm.stats.results.conspec.contrasts = Inf;
matlabbatch{6}.spm.stats.results.conspec.threshdesc = 'none';
matlabbatch{6}.spm.stats.results.conspec.thresh = 0.001;
matlabbatch{6}.spm.stats.results.conspec.extent = 0;
matlabbatch{6}.spm.stats.results.conspec.conjunction = 1;
matlabbatch{6}.spm.stats.results.conspec.mask.none = 1;
matlabbatch{6}.spm.stats.results.units = 1;
matlabbatch{6}.spm.stats.results.export{1}.png = true;
